### ISSUE TITLE
Windy Icon Suggestion

### ISSUE THREAD

**Issue by SenorKarlos** [5310/discord-bot-castform#12]
I've just added this locally, not worth the work of a PR or anything, but I think this looks better and matches PoGo weather icons better - 🪁

First windy i got during testing I was like holy crap a damn cyclone??? 😂

**Comment by 5310** [comment]
Legit issue! :cyclone::scream:

I think the reason we used the cyclone emoji was because we didn't have a kite on Discord back when the first version was written. And since then our local instance has actually switched to the kite, but I totally forgot to update the main code. Will do ASAP and update this issue :)

**Comment by 5310** [comment]
It is done :kite:
