### ISSUE TITLE
[Feature Request] Send only verified weather

### ISSUE THREAD

**Issue by kamieniarz** [5310/discord-bot-castform#8]
So what I'd like to ask for is an option to set known hours of weather imports from accuweather to pogo. If weather gets updated for 8 hours it means it's updating 3 times a day. By example if it's 5am, 1pm and 9pm then in config file (or somewhere else) could be sth like `UPDATE HOURS =` where I could write eg `[05, 13, 21]` what would make my discord bot send weather forecast at these hours (instead of sending it each hour) for the next 8h instead of 12h.

Right now bot is sending mostly irrelevent messeges (since I know when weather gets updated in pogo) so it would be great to have such an option to simply receive only 3 messages per day with predicted weather for the next 8h per message.

It could even look like that to keep it simple
![Bez tytułu](https://user-images.githubusercontent.com/9063907/71176358-f8d76e80-2269-11ea-9441-74db4471a36f.png)

**Comment by 5310** [comment]
This is what the first version of the bot was like, and it was very often wrong.

Which is to say the known hours of AW pulls from a year ago did not hold up. 

The middle one was most often wrong— neither `12` nor `13` were not good all the time. This might just well be biased because those were our most observed waking hours. But they certainly weren't enough— maybe there is another underlying pattern to that error, but we couldn't see one. This is why we switched to the full hourly queries in the first place for v2.

However, if you think the eight-hourly pull model _is_ still correct, you could run the bot with [these lines](https://github.com/5310/discord-bot-castform/blob/v2/index.js#L158-L162) edited to start with: 

```js
        CB.timer(DateTime.fromObject({
          hour: 5,
          minute: location.minute || 0,
          zone: location.timezone
        }).toJSDate(), 8 * 60 * 60 * 1000),
```

**Comment by kamieniarz** [comment]
Works nice, thanks. Any idea how to make such an output as on screenshot? I'm not good at this stuff... I'd like to have only 8 hours ahead and only two columns: hours and weather. I don't want to have empty icons and clocks above
![Bez tytułu](https://user-images.githubusercontent.com/9063907/71301897-46a4c180-23a5-11ea-809d-bdce0bdfb9e3.png)

**Comment by 5310** [comment]
@kamieniarz let me know if this works: [v2-8hourly/index.js](https://github.com/5310/discord-bot-castform/blob/v2-8hourly/index.js)

 I did test it, but then I ran out of API calls while cleaning it up.

**Comment by kamieniarz** [comment]
It works in new branch but I resigned from using it cause weather pulls are pretty random (still) :/
